spring.application.name=banking_management

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/banking-management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===== JWT =====
app.jwt.secret=rikkei-bank-super-secret-key-256bit-minimum-required-length-here
app.jwt.access-token-expiration-ms=300000
app.jwt.refresh-token-expiration-ms=86400000

# ===== File Upload =====
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ===== Logging =====
logging.level.com.banking_management=DEBUG
logging.level.org.springframework.security=DEBUG

# Cloudinary
cloudinary.cloud-name=dtdpmvyzq
cloudinary.api-key=832254241169418
cloudinary.api-secret=hLQ4s1U8qINkSogzFLmxn2UGdMs